name: build
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Copier code depuis Github vers notre serveur Ubuntu
        uses: actions/checkout@v3
      - name: Installer nodeJS sur notre serveur Ubuntu
        uses: actions/setup-node@v3
      - name : installation des packages JS
        run: npm install
      - name : Lancer la politique de tests disponible
        run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copier code depuis Github vers notre serveur Ubuntu
        uses: actions/checkout@v3
      - name: Installer nodeJS
        uses: actions/setup-node@v3
      - name : installation des packages JS
        run: npm install
      - name: Build l'application
        run: npm run build
